#pragma once


enum E_EDGE
{
    EDGE_LEFT = 0, EDGE_TOP, EDGE_RIGHT, EDGE_BOTTOM, EDGE_END
};

enum E_SHAPE
{
    SHAPE_RECT = 0, SHAPE_CIRCLE, SHAPE_ELLIPSE, SHAPE_END
};

enum E_WEAPON_TYPE
{
    WEAPON_BULLET = 0, WEAPON_BUCKSHOT, WEAPON_TSAR, WEAPON_END
};

enum E_IMAGE_LOAD_KIND
{
    LOAD_EMPTY, LOAD_FILE, LOAD_END
};

enum E_UNIT_TYPE
{
    UNIT_HEAD = 0, UNIT_BODY, UNIT_TAIL
};

enum E_ITEM_TYPE
{
    ITEM_TYPE_1 = 0, ITEM_TYPE_2, ITEM_TYPE_3
};